### ISSUE TITLE
Link?

### ISSUE THREAD

**Issue by EndreEndi** [BackToAction/BTACore#1]

**Comment by HyGlobalHD** [comment]
The plugin still in closed-development as it is not tested yet, however i already write the basic of the code (API) and I hope you can wait for a while. Sorry for the inconvenience .
P/S: I Right Now Quite Busy And The Code Is With Me So The Others Developer Can't Upload It. ;)

**Comment by HyGlobalHD** [comment]
I just upload latest development and you can view our changelog for more informations thank you. @MateiGamingYTB

**Comment by EndreEndi** [comment]
Can u give a link to test it?

**Comment by HyGlobalHD** [comment]
@MateiGamingYTB the plugin still in development and it an APIs plugin which you'll need to make a plugin to depend on this plugin, for example making a shop plugin by depending in this plugin's currencyAPI

**Comment by EndreEndi** [comment]
hmmm.......ok.....

**Comment by EndreEndi** [comment]
you have discord? if u have can give to me?

**Comment by HyGlobalHD** [comment]
@MateiGamingYTB HyGlobalHD#2182
